apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
  #namespace: config-management-system
spec:
  clusterName: minikube
  git:
    syncRepo: https://github.com/wfblockchain/poc-config-sync
    secretType: none
    policyDir: policy
